### PR TITLE
LPoint : New ammo and logistic object

### PR DESCRIPTION
**Pull request by Vdauphin**
Add Ammobox from ACE3.
Add logistic object : fuel tank and wheel.

### CODE REVIEW

**Comment by Giallustio** [comment]
AFAIk you can lift the B_cargoNet_01_ammo_F with my lift

**Comment by Vdauphin** [comment]
I like to use little bird for B_cargoNet_01_ammo_F lifting. So I lowered the mass to 500 kg. 

I prefer use the sling loading system from ARMA3. The Arma 3 lifting is more accessible due to native implementation and is commonly used on servers.

Give the choose between the two lifting system to player could be a good idea ?

**Comment by Giallustio** [comment]
Did you test it in MP?
AFAIK the mass is set locally and remain local.
My lift is an integration of the A3 lift, did you try it?

**Comment by Vdauphin** [comment]
Yes I tried this in MP, it is currently running on our server and is working well. The mass is may be set locally but I think is brodcast to player (look at https://community.bistudio.com/wiki/setMass  = Category:Commands with global effects).

I saw your lift system, is working well but as I said sling loading system is know by player.

**Comment by Giallustio** [comment]
yeah probably they've changed it

**Pull request closed without merging**
