### PR TITLE
Spawn info_hideout or info_cache if all cache or hideout found

### PR DESCRIPTION
**Pull request by Vdauphin**
Spawn info_cache if all hideout are found and all cache not found.
Spawn info_hideout if all cache are found and all hideout not found.

If all cache and hideout found spawn "no intel".

### CODE REVIEW

**Comment by Giallustio** [comment]
Cache will always spawn, there's no limit

**Comment by Vdauphin** [comment]
Sorry, did you change it from your initial release ?

**Comment by Giallustio** [comment]
they've always been this way

**Comment by Vdauphin** [comment]
I was talking about hideout x) , never mind ...
Is it a normal behavior when you find all hideout and you can't get intel for ammo cache ?

**Comment by Giallustio** [comment]
No, you're right, I'll look into it. I've never managed to get that far :)

**Comment by Giallustio** [comment]
https://github.com/Giallustio/HeartsAndMinds/commit/d4a55d716184269ce19eeb8d331b9a8f73e77e6f

**Pull request closed without merging**
