### PR TITLE
FIX : btc_patrol_active is negative

### PR DESCRIPTION
**Pull request by Vdauphin**
This should prevent this issue https://github.com/Giallustio/HeartsAndMinds/issues/81

Don't add  addEventHandler "Killed" to unit in vehicule, only for leader.
Next : If they GetOut,  add addEventHandler "Killed"

### CODE REVIEW

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/commit/800dbcd8a10125be4bc6fea5b2911b1025a35f35 will add too much EH for a veh

**Comment by Vdauphin** [comment]
I am working on a different approch.

**Comment by Giallustio** [comment]
I've lost you here

**Comment by Vdauphin** [comment]
doesn't matter the (https://github.com/Giallustio/HeartsAndMinds/pull/83) replace it ! :)

**Pull request closed without merging**
