### PR TITLE
FIX : btc_helo_1 will never respawn

### PR DESCRIPTION
**Pull request by Vdauphin**
btc_helo_1 will never respawn and can't be tow

### CODE REVIEW

**Comment by Giallustio** [comment]
I'm gonna add the A3 vehicle respawn module

**Comment by Vdauphin** [comment]
I used but for unknow reason when a vehicule is hit by an enemy, the vehicule never respawn. But if a player destroy it, the vehicule respawn. 
So check ;)

**Comment by Giallustio** [comment]
I'll do it before the new release! Thank you!
Did you try the new database functions?

**Comment by Vdauphin** [comment]
Nop sorry, I have a server running on your old HAM released and my ACE3 interaction and I don't want to lose our game progress.
I am waiting for ARM3 or ACE3 update to test your update.

**Comment by Giallustio** [comment]
Nice! Let me know when you'll try it!

**Comment by Vdauphin** [comment]
First test  : The ARMA3 respawn module work :) :+1:

**Comment by Vdauphin** [comment]
Second test : The ARMA3 respawn module is NOT working :( :-1:

**Comment by Giallustio** [comment]
if it's still not working i'm gonna restore the old fnc

**Comment by Vdauphin** [comment]
The  ARMA3 respawn module is not working perfectly, for me it is still an issue.
Did you tested ?

**Comment by Giallustio** [comment]
it worked in our session

**Comment by Vdauphin** [comment]
I did some test and I saw when you try to land with a heli on water (approche slowly the heli to sea surface). The heli sink in water. And after a few seconds, the heli is destroyed. 
You can check it   getdammage command.
Infortunately, in that case , the heli never respawn.

**Pull request closed without merging**
