### PR TITLE
FIX civil traffic 

### PR DESCRIPTION
**Pull request by Vdauphin**
addeventhandler syntax precision
remove "del" variable

### CODE REVIEW

**Comment by Vdauphin** [comment]
Did you try this FIX ?

**Comment by Giallustio** [comment]
I can't understand why it should work

**Comment by Vdauphin** [comment]
But it works :) , I tested it yesterday and today, just give it a try !

**Comment by Giallustio** [comment]
yeah, it's linked with the other commit, i couldn't understand in this one

**Comment by Vdauphin** [comment]
for me the syntax is : 
object addEventHandler [type, {command1; command2;}];
or object addEventHandler [type, "command1; command2;"];
For me you wrote :  object addEventHandler [type, command1; command2;];

But I am not very sure about that

**Comment by Vdauphin** [comment]
I tested your commit  https://github.com/Giallustio/HeartsAndMinds/commit/4d5aef53957883c22fc3e24c3f9059f646d11826  and in the editor, it is still an issue for me.

**Comment by Vdauphin** [comment]
Exemple :
code = "command1; command2;";
myfunc = compile code;

compile return code (not a string) so :
object addEventHandler [type, {myfunc}];
or object addEventHandler [type, "myfunc"];

**Comment by Giallustio** [comment]
Yeah it's not working, i've to re make it.
actually it's a code, so i wrote [type, {}]

**Comment by Vdauphin** [comment]
For me the correct way is _veh addEventHandler ["HandleDamage", {btc_fnc_civ_traffic_hd}];
and everything should work correctly :)

**Comment by Giallustio** [comment]
Could you take a look at my last commit? It should work now

**Pull request closed without merging**
