### PR TITLE
Add : Interrogate Prisoner

### PR DESCRIPTION
**Pull request by Vdauphin**
Now you can interrogate enemies you captured (https://github.com/Giallustio/HeartsAndMinds/issues/59#issuecomment-162385739).
- you need to be interpreter to understand.
- prisoner have a random number of intel more or less interesting.
- prisoner having too much pain can't be interrogate (complain).
- prisoner interrogated and killed, will not give body intel.

### CODE REVIEW

**Comment by Giallustio** [comment]
can't merge

**Comment by Vdauphin** [comment]
Should be ok now ;)

**Comment by Giallustio** [comment]
Prisoners in base never de-spawn?

**Comment by Vdauphin** [comment]
I dont know, normally not because there are out of range of thé cleaning function.
I dont think is a big problem , is it ?

**Comment by Giallustio** [comment]
well....it depends by the numbers. It's better to bring them back to their place :D

**Comment by Vdauphin** [comment]
I am sure, players will resolve the problem by their own ;)

**Comment by Vdauphin** [comment]
Or it could be a side mission : exfilter prisoners...

**Comment by Giallustio** [comment]
Maybe, or just let the players decide how to play, it's not a big deal. Well, maybe 50 prisoners in base could be, but we'll see when and if the problem will occur

**Comment by Vdauphin** [comment]
I like this idea ;D

**Pull request merged**
