### PR TITLE
Add enemy AAF (A3) 

### PR DESCRIPTION
**Pull request by Vdauphin**
You can now play against AAF (A3).
You can choose this side mission parameter at start

### CODE REVIEW

**Comment by Giallustio** [comment]
I was thinking to rewrite the entire system and allow to play the mission as opfor or resistance

**Comment by Vdauphin** [comment]
I implemented the AAF for their green skin and heavy armor. Are you gonna keep this enemy side ?

**Comment by Giallustio** [comment]
Since i'm switching to RHS, i'm gonna add the insurgency from RHS and I'll gonna add support for the green side, slightly different from your implementation tho

**Comment by Vdauphin** [comment]
Hello !
Use RHS mod is very nice. But when I am looking for a mission, I download mission without  mod.
For me a mod need to be add in a mission if it  adds new gameplay like ACE3.
If the mod is just adding skin, may be it could be optional instead?

**Comment by Giallustio** [comment]
The core doesn't need RHS, just remove the reference in mission.sqm.
The only real requirement is ACE and CBA

**Pull request closed without merging**
