### PR TITLE
FIX-vehicle-get-stuck

### PR DESCRIPTION
**Pull request by Vdauphin**
When a vehicle is stuck for long time, vehicle runs out of fuel. 
Now, the server remove civil vehicle when out of fuel

### CODE REVIEW

**Comment by Giallustio** [comment]
Got it.
btc_fnc_civ_traffic_hd should be changed, i like the idea, i'm gonna implement this.
Maybe even a GetOut could be usefull!

**Comment by Vdauphin** [comment]
GetOut is a good idea too but sometimes the civ getin back,  what btc_fnc_civ_traffic_hd will do in this case ?

**Comment by Giallustio** [comment]
it will delete it if players are far away, i'll look into it asap

**Comment by Vdauphin** [comment]
Perfect !

**Pull request closed without merging**
